apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: ctse2024/user-service:${{ github.run_id }}
        ports:
        - containerPort: 5002
